package com.meetup.contactmanager.entities;
// Generated Oct 15, 2013 5:40:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name="company"
    ,catalog="meetup"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Company  implements java.io.Serializable {


     private Integer companyId;
     private String name;
     private Set<Contact> contacts = new HashSet<Contact>(0);

    public Company() {
    }

	
    public Company(String name) {
        this.name = name;
    }
    public Company(String name, Set<Contact> contacts) {
       this.name = name;
       this.contacts = contacts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="company_id", unique=true, nullable=false)
    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
    
    @Column(name="name", unique=true, nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="company")
    public Set<Contact> getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Set<Contact> contacts) {
        this.contacts = contacts;
    }




}


