package com.meetup.contactmanager.entities;
// Generated Oct 15, 2013 5:40:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name="contact"
    ,catalog="meetup"
)
public class Contact  implements java.io.Serializable {


     private Integer contactId;
     private Company company;
     private String name;
     private String userId;
     private String title;
     private Integer memberId;
     private Date joinedGroupOn;
     private Date lastVisitedGroupOn;
     private Date lastAttended;
     private Short totalRsvps;
     private Short rsvpedYes;
     private Short rsvpedMaybe;
     private Short rsvpedNo;
     private Short meetupsAttended;
     private Short noShows;
     private Character intro;
     private Character photo;
     private Character assistantOrganizer;
     private String mailingList;
     private String memberProfileUrl;
     private String phone;

    public Contact() {
    }

	
    public Contact(Company company, String userId) {
        this.company = company;
        this.userId = userId;
    }
    public Contact(Company company, String name, String userId, String title, Integer memberId, Date joinedGroupOn, Date lastVisitedGroupOn, Date lastAttended, Short totalRsvps, Short rsvpedYes, Short rsvpedMaybe, Short rsvpedNo, Short meetupsAttended, Short noShows, Character intro, Character photo, Character assistantOrganizer, String mailingList, String memberProfileUrl, String phone) {
       this.company = company;
       this.name = name;
       this.userId = userId;
       this.title = title;
       this.memberId = memberId;
       this.joinedGroupOn = joinedGroupOn;
       this.lastVisitedGroupOn = lastVisitedGroupOn;
       this.lastAttended = lastAttended;
       this.totalRsvps = totalRsvps;
       this.rsvpedYes = rsvpedYes;
       this.rsvpedMaybe = rsvpedMaybe;
       this.rsvpedNo = rsvpedNo;
       this.meetupsAttended = meetupsAttended;
       this.noShows = noShows;
       this.intro = intro;
       this.photo = photo;
       this.assistantOrganizer = assistantOrganizer;
       this.mailingList = mailingList;
       this.memberProfileUrl = memberProfileUrl;
       this.phone = phone;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="contact_id", unique=true, nullable=false)
    public Integer getContactId() {
        return this.contactId;
    }
    
    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id", nullable=false)
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="user_id", nullable=false, length=45)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    
    @Column(name="title", length=45)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="member_id")
    public Integer getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="joined_group_on", length=10)
    public Date getJoinedGroupOn() {
        return this.joinedGroupOn;
    }
    
    public void setJoinedGroupOn(Date joinedGroupOn) {
        this.joinedGroupOn = joinedGroupOn;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="last_visited_group_on", length=10)
    public Date getLastVisitedGroupOn() {
        return this.lastVisitedGroupOn;
    }
    
    public void setLastVisitedGroupOn(Date lastVisitedGroupOn) {
        this.lastVisitedGroupOn = lastVisitedGroupOn;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="last_attended", length=10)
    public Date getLastAttended() {
        return this.lastAttended;
    }
    
    public void setLastAttended(Date lastAttended) {
        this.lastAttended = lastAttended;
    }
    
    @Column(name="total_rsvps")
    public Short getTotalRsvps() {
        return this.totalRsvps;
    }
    
    public void setTotalRsvps(Short totalRsvps) {
        this.totalRsvps = totalRsvps;
    }
    
    @Column(name="rsvped_yes")
    public Short getRsvpedYes() {
        return this.rsvpedYes;
    }
    
    public void setRsvpedYes(Short rsvpedYes) {
        this.rsvpedYes = rsvpedYes;
    }
    
    @Column(name="rsvped_maybe")
    public Short getRsvpedMaybe() {
        return this.rsvpedMaybe;
    }
    
    public void setRsvpedMaybe(Short rsvpedMaybe) {
        this.rsvpedMaybe = rsvpedMaybe;
    }
    
    @Column(name="rsvped_no")
    public Short getRsvpedNo() {
        return this.rsvpedNo;
    }
    
    public void setRsvpedNo(Short rsvpedNo) {
        this.rsvpedNo = rsvpedNo;
    }
    
    @Column(name="meetups_attended")
    public Short getMeetupsAttended() {
        return this.meetupsAttended;
    }
    
    public void setMeetupsAttended(Short meetupsAttended) {
        this.meetupsAttended = meetupsAttended;
    }
    
    @Column(name="no_shows")
    public Short getNoShows() {
        return this.noShows;
    }
    
    public void setNoShows(Short noShows) {
        this.noShows = noShows;
    }
    
    @Column(name="intro", length=1)
    public Character getIntro() {
        return this.intro;
    }
    
    public void setIntro(Character intro) {
        this.intro = intro;
    }
    
    @Column(name="photo", length=1)
    public Character getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(Character photo) {
        this.photo = photo;
    }
    
    @Column(name="assistant_organizer", length=1)
    public Character getAssistantOrganizer() {
        return this.assistantOrganizer;
    }
    
    public void setAssistantOrganizer(Character assistantOrganizer) {
        this.assistantOrganizer = assistantOrganizer;
    }
    
    @Column(name="mailing_list", length=45)
    public String getMailingList() {
        return this.mailingList;
    }
    
    public void setMailingList(String mailingList) {
        this.mailingList = mailingList;
    }
    
    @Column(name="member_profile_url", length=200)
    public String getMemberProfileUrl() {
        return this.memberProfileUrl;
    }
    
    public void setMemberProfileUrl(String memberProfileUrl) {
        this.memberProfileUrl = memberProfileUrl;
    }
    
    @Column(name="phone", length=10)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


